// react-with-vite/src/App.tsx
import { useEffect, useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { Button } from "antd";
import { axios } from "@/package/axios";
import TableTest from "./page/TableTest";
import LazyLoadImage from "./hooks/lazyload";
import flower from "@/assets/images/flower.jpg";

function App() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    getList();
  }, []);

  const getList = async () => {
    const res = await axios.get("/pic");
    console.log(res);
  };

  return (
    <>
      <div className="main">
        <Button>Button</Button>
        <TableTest></TableTest>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <LazyLoadImage src={flower} alt="" />
    </>
  );
}

export default App;

// vue-with-vite/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import HelloWorld from './components/HelloWorld.vue'
// import axios from '@/package/axios';

const list = ref<any>([])
async function getList() {
  // const res = await axios.get('/pic')
  // console.log(res);
  // list.value = res.data
}
getList()
</script>

<template>
  <div class="main">
    halo
    <div v-for="item of list" :key="item.age">
      <div>name: {{ item.name }}</div>
      <div>age: {{ item.age }}</div>
    </div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.main {
  height: 300vh;
}
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
